site_name: Oxxo Vision Project Documentation

nav:
  - Home: index.md
  - Arquitectura: arquitectura.md
  - Tecnología de Visión Artificial: vision-artificial.md
  - Guía de Instalación: instalacion.md
  - MyOxxo Mobile App: app.md

theme: 
  name: material
  palette:
    primary: red
    accent: orange
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/femsa/oxxo-vision
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/oxxo_oficial
